<?php require_once __DIR__ . '/includes/header.php'; ?>
<?php require_once __DIR__ . '/../helpers/view_helper.php'; ?>

<div class="container">
    <div class="dashboard-header">
        <h2>Reports Management</h2>
        <p>Generate and view system reports</p>
    </div>
    
    <?php showMessage(); ?>
    
    <div class="card">
        <h3>Generate New Report</h3>
        <form method="POST" action="<?php echo base_url('index.php?page=reports'); ?>">
            <div class="form-group">
                <label>Report Type:</label>
                <select name="report_type" required>
                    <option value="users">Users Report</option>
                    <option value="projects">Projects Report</option>
                    <option value="payments">Payments Report</option>
                    <option value="disputes">Disputes Report</option>
                </select>
            </div>
            <button type="submit" name="generate_report" class="btn">Generate Report</button>
        </form>
    </div>
    
    <div class="card">
        <h3>Generated Reports</h3>
        <div class="table">
            <table style="width: 100%;">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Type</th>
                        <th>Generated By</th>
                        <th>Created</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($reports)): ?>
                        <tr>
                            <td colspan="5" style="text-align: center; padding: 30px;">
                                No reports generated yet.
                            </td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($reports as $report): ?>
                            <tr>
                                <td><?php echo $report['id']; ?></td>
                                <td><?php echo ucfirst($report['type']); ?></td>
                                <td>Admin</td>
                                <td><?php echo date('M j, Y H:i', strtotime($report['createdAt'])); ?></td>
                                <td>
                                    <a href="<?php echo base_url('index.php?page=reports&action=export&id=' . $report['id'] . '&format=csv'); ?>" class="btn btn-sm">Export CSV</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="admin-actions" style="margin-top: 20px;">
        <a href="<?php echo base_url('index.php?page=dashboard'); ?>" class="btn">Back to Dashboard</a>
    </div>
</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>

